-- MySQL Script generated by MySQL Workbench
-- Mon Aug  2 14:25:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema learning_english
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema learning_english
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `learning_english` DEFAULT CHARACTER SET utf8 ;
USE `learning_english` ;

-- -----------------------------------------------------
-- Table `learning_english`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learning_english`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learning_english`.`vocabularies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learning_english`.`vocabularies` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `key` TEXT NULL,
  `value` TEXT NULL,
  `note` TEXT NULL,
  `example` TEXT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`vocabulary_id`),
  INDEX `fk_vocabularies_user_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_vocabularies_user`
    FOREIGN KEY (`id`)
    REFERENCES `learning_english`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
